version: '3'
services:

  web:
    image: vames1/my-web-app:latest
    container_name: web-server
    ports:
      - "8082:80"
    networks:
      - myapp-network
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: RootPass@2026!
      MYSQL_DATABASE: myappdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: AdminPass@2026!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - myapp-network
    restart: always

networks:
  myapp-network:
    driver: bridge

volumes:
  db-data:
